re_split: false

lr: 1e-2
n_epochs: 200
n_iters: 50
weight_decay: 5e-4

n_hidden: 16
dropout: 0.5
input_dropout: 0.0   # cora:0.8,citeseer:0.0

k: 9
tolerance: 0.01
threshold: 0.5

#lpcls: 5

# below is for saving results
save_graph: false